blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ Feature requests
    url: https://github.com/callstack/react-native-builder-bob/discussions/new?category=ideas
    about: Suggest an idea.
  - name: ğŸ™ Question
    url: https://github.com/callstack/react-native-builder-bob/discussions/new?category=q-a
    about: Choose if you need help.
