name: Comment template diffs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/comment-diffs.yml'
      - 'packages/create-react-native-library/**'
      - '!**.md'

jobs:
  generate-diffs-if-needed:
    name: Generate diffs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy config matrix to persist it
        run: |
          mkdir ../configMatrix
          cp ./.github/workflows/configMatrix.sh ../configMatrix/

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Build crnl
        run: |
          yarn workspace create-react-native-library prepare
      
      - name: Create old version libraries
        run: |
          # Source all the configuration values to load $languages, $types, and $exclude
          source ../configMatrix/configMatrix.sh

          create_library() {
            library_type=$1
            language=$2

            echo "Generating $library_type/$language"
            path_prefix="../test/$library_type/$language"
            target_path="$path_prefix/new-version"

            npx create-react-native-library "$target_path" \
              --slug @bob/react-native-test \
              --description test \
              --author-name test \
              --author-email test@test \
              --author-url https://test.test \
              --repo-url https://test.test \
              --type "$library_type" \
              --languages "$language" \
              --no-example \
              --no-local \
              --react-native-version 0.73.0-rc.2 

            # Remove the .git folder of the created library
            rm -rf "$target_path/.git"
          }

          for library_type in "${libraryTypes[@]}"; do
            for language in "${languages[@]}"; do
              if [[ ! "${exclude[*]}" =~ ${library_type}/${language} ]]; then
                create_library "$library_type" "$language"
              fi
            done
          done
      
      # - name: Setup again # Add a check here to setup again if deps changed
      #   uses: ./.github/actions/setup
      
      - name: Remove old build and build again
        run: |
          rm -rf ./packages/create-react-native-library/lib
          yarn workspace create-react-native-library prepare
      
      - name: Create library again
        run: |
          # Source all the configuration values to load $languages, $types, and $exclude
          source ../configMatrix/configMatrix.sh

          git fetch origin main
          git checkout origin/main

          create_library() {
            library_type=$1
            language=$2

            echo "Running $library_type/$language"
            path_prefix="../test/$library_type/$language"
            target_path="$path_prefix/old-version"

            npx create-react-native-library "$target_path" \
              --slug @bob/react-native-test \
              --description test \
              --author-name test \
              --author-email test@test \
              --author-url https://test.test \
              --repo-url https://test.test \
              --type "$library_type" \
              --languages "$language" \
              --no-example \
              --no-local \
              --react-native-version 0.73.0-rc.2 

            # Remove the .git folder of the created library
            rm -rf "$target_path/.git"
          }

          for library_type in "${libraryTypes[@]}"; do
            for language in "${languages[@]}"; do
              if [[ ! "${exclude[*]}" =~ ${library_type}/${language} ]]; then
                create_library "$library_type" "$language"
              fi
            done
          done

      - name: Switch to diffs branch
        run: |
          desired_branch="diffs"
          # Check if the branch exists on the remote repository
          if git ls-remote --heads origin "$desired_branch" | grep -q "$desired_branch"; then
            echo "The branch $desired_branch already exists on the remote repository."
            git fetch origin "$desired_branch"  # Fetch the branch from the remote
            git checkout "$desired_branch"     # Switch to the existing branch
          else
            echo "The branch $desired_branch does not exist on the remote repository."
            git checkout -b "$desired_branch"  # Create a new branch and switch to it
          fi

      - name: Initiate diffs
        run: |
          # Source all the configuration values to load $languages, $types, and $exclude
          source ../configMatrix/configMatrix.sh

          output_path="../output"
          output_file="$output_path/output.txt"

          mkdir -p "$output_path"

          function copy_commit_diff(){
            library_type=$1
            language=$2

            path_prefix="../test/$library_type/$language"
            target_path_new_version="$path_prefix/new-version"
            target_path_old_version="$path_prefix/old-version"

            # Remove everything except the .git folder
            for i in $(ls | grep -v ".git") ; do rm -rf "$i"; done;

            # Copy the old version
            cp -r "$target_path_old_version/." .

            git config --global user.email "text@test.com"
            git config --global user.name "Github actions test"

            # Add all files and commit
            git add -A || true && git commit -m "Automatic commit" || true

            # Remove everything except the .git folder
            for i in $(ls | grep -v ".git") ; do rm -rf "$i"; done;

            # Copy the new version
            cp -r "$target_path_new_version/." .

            # Add all files and commit
            git add -A || true && git commit -m "Automatic commit" || true

            # echo diff
            echo $(git diff HEAD~)

            # Check if there is a diff
            if git diff --quiet HEAD~; then
              echo "No diff"
            else
              # Push the branches
              git push --set-upstream origin diffs

              # Get new version remote commit hash
              new_version_commit_hash=$(git rev-parse --short origin/diffs)

              # Get old version remote commit hash
              old_version_commit_hash=$(git rev-parse --short origin/diffs~)

              # Add output to file
              echo "[$library_type/$language](https://github.com/${{github.repository}}/compare/$old_version_commit_hash..$new_version_commit_hash)" >> "$output_file"

              # Add empty line
              echo \ >> $output_file
            fi
          }

          for library_type in "${libraryTypes[@]}"; do
            for language in "${languages[@]}"; do
              if [[ ! "${exclude[*]}" =~ ${library_type}/${language} ]]; then
                copy_commit_diff "$library_type" "$language"
              fi
            done
          done


      # - uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Clean the Differ repo
        run: |
          cd differ
          # Remove everything except the .git folder and it's contents.
          for i in `ls | grep -v ".git"` ; do rm -rf $i; done;

      - name: Delete .git of new-version
        run: |
          rm -rf new-version/.git

      - name: Copy everything inside new-version to differ
        run: |
          cp -r new-version/* differ

      - name: Commit everything in differ
        id: commit-new
        run: |
          git config --global user.email "text@test.com"
          git config --global user.name "Github actions test"
          cd differ
          git add -A || true && git commit -m "Automatic commit" || true

      - name: Switch to old version repo
        run: |
          cd differ
          desired_branch="${{ env.OLD_VERSION_BRANCH }}"
          # Check if the branch exists on the remote repository
          if git ls-remote --heads origin "$desired_branch" | grep -q "$desired_branch"; then
            echo "The branch $desired_branch already exists on the remote repository."
            git fetch origin "$desired_branch"  # Fetch the branch from the remote
            git checkout "$desired_branch"     # Switch to the existing branch
          else
            echo "The branch $desired_branch does not exist on the remote repository."
            git checkout -b "$desired_branch"  # Create a new branch and switch to it
          fi

      - name: Clean the Differ repo
        run: |
          cd differ
          # Remove everything except the .git folder and it's contents.
          for i in `ls | grep -v ".git"` ; do rm -rf $i; done;

      - name: Delete .git of old-version
        run: |
          rm -rf old-version/.git

      - name: Copy everything inside new-version to differ
        run: |
          cp -r old-version/* differ

      - name: Commit everything in differ
        run: |
          git config --global user.email "text@test.com"
          git config --global user.name "Github actions test"
          cd differ
          git add -A || true && git commit -m "Automatic commit" || true


      - name: Check if the diff is non-empty
        id: check-is-diff-non-empty
        run: |
          cd differ
          if git diff --quiet ${{ env.OLD_VERSION_BRANCH }}..${{ env.NEW_VERSION_BRANCH }}; then
            result=0 # Diff is empty
          else
            result=1 # Diff is not empty
          fi
          echo "DIFF_IS_NON_EMPTY=$result" >> $GITHUB_OUTPUT
          
      - name: Push repos
        if: ${{ steps.check-is-diff-non-empty.outputs.DIFF_IS_NON_EMPTY == '1' }}
        id: push
        run: |
          cd differ
          git push --set-upstream origin ${{ env.OLD_VERSION_BRANCH }}
          echo "OLD_COMMIT_HASH=$(git rev-parse --short origin/${{ env.OLD_VERSION_BRANCH }})" >> $GITHUB_OUTPUT
          git checkout ${{ env.NEW_VERSION_BRANCH }}
          git push --set-upstream origin ${{ env.NEW_VERSION_BRANCH }}
          echo "NEW_COMMIT_HASH=$(git rev-parse --short origin/${{ env.NEW_VERSION_BRANCH }})" >> $GITHUB_OUTPUT

      - name: Write changes to common file
        if: ${{ steps.check-is-diff-non-empty.outputs.DIFF_IS_NON_EMPTY == '1' }}
        run: |
          mkdir outputs
          echo "- [${{ matrix.language }} ${{ matrix.type }}](https://github.com/${{ vars.DIFF_VIEW_USERNAME }}/${{ vars.DIFF_VIEW_REPO_NAME }}/compare/${{ steps.push.outputs.OLD_COMMIT_HASH }}..${{ steps.push.outputs.NEW_COMMIT_HASH }})" >> outputs/${{ matrix.type }}-${{ matrix.language }}.txt

      - uses: actions/upload-artifact@v3
        if: ${{ steps.check-is-diff-non-empty.outputs.DIFF_IS_NON_EMPTY == '1' }}
        with:
          name: outputs
          path: outputs/*.txt

  read-artifacts-and-comment:
    name: Read the artifacts and comment
    runs-on: ubuntu-latest
    needs: [generate-diffs-if-needed]
    steps:
      - name: Load outputs
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: outputs
          path: outputs

      - name: Output artifacts
        id: artifacts
        run: |
          if ls outputs/*.txt; then
            result=1 # Artifacts are not empty
            echo "ARTIFACTS<<EOF" >> $GITHUB_OUTPUT
            cat outputs/*.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

          else
            result=0 # Artifacts are empty
          fi

          echo "ARTIFACTS_ARE_NON_EMPTY=$result" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: ${{ steps.artifacts.outputs.ARTIFACTS_ARE_NON_EMPTY == '1' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const replaceTable = {
              "module-legacy": "Native module",
              "module-mixed": "Turbo module with backward compat",
              "module-new": "Turbo module",
              "view-legacy": "Native view",
              "view-mixed": "Fabric view with backward compat",
              "view-new": "Fabric view",
              "java-objc": "Java and Objective C",
              "java-swift": "Java and Swift",
              "kotlin-objc": "Kotlin and Objective C",
              "kotlin-swift": "Kotlin and Swift"
            }

            const artifacts = `${{ steps.artifacts.outputs.ARTIFACTS }}`;

            const artifactsReplaced = Object.entries(replaceTable).reduce((acc, [key, value]) => {
              return acc.replace(new RegExp(key, "g"), value);
            }, artifacts)

            const body = `ðŸ¤“â˜ï¸ This PR changes the output of \`create-react-native-library\`. You can find the diffs of effected templates below:

            ${artifactsReplaced}
            `;

            const comments = await github.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            if (comments.data.some(comment => comment.body === body)) {
              return;
            }
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
          
